### ISSUE TITLE
DeepChem 2.7.0 Release Tracker

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#3109]
- [x] MDTRaj support doesn't work on windows. Raise issue on mdtraj to document
- [x] Turn off mdtraj installation for windows build since build is currently failing on windows
- [ ] ~Update docker image for 2.7.0 (#3116, Nov 24th)~ (see note below)
- [x] Put together release notes for 2.7.0 (Nov 29th)
- [x] Make release tag and other release steps (Nov 30th)

**Comment by arunppsg** [comment]
Note: docker image update is targeted for 2.7.1

**Comment by rbharath** [comment]
We made 2.7.1 a bugfix release to fix an issue in pip. Closing this release tracker since the release has been made
