### ISSUE TITLE
DeepChem 2.7.2 Release Tracker (Target Jan 30, 2023)

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#3131]
Roadmap
----------
- [ ] Fix TensorFlow 2.11 issues
- [ ] Remove Simdna dependency
- [ ] Report pymatgen breakage to their dev team
- [ ] Make mypy fixes for latest version
- [ ] Put up pretraining design for review

Issue Triage
------------
- [x] #2956 by @advikavs 
- [ ] #3120 by @maithili232
- [ ] #3129 by @arunppsg 
- [x] https://github.com/deepchem/deepchem/issues/3130 by @advikavs 
- [ ] https://github.com/deepchem/deepchem/issues/3133 by @maithili232

**Comment by rbharath** [comment]
Closing since this is out of date. Will put up a new release tracker once we are near the next release
